### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Ammoniya** [Niweera/exslt#1]
@Niweera Could you please look into this matter ;-) 
```Uncaught TypeError: Cannot read property 'split' of undefined```

![image](https://user-images.githubusercontent.com/20130001/88459212-475c8380-ceb1-11ea-906a-98ddfc0854f9.png)

**Comment by Niweera** [comment]
Have you used the latest release?

**Comment by Ammoniya** [comment]
Great job @Niweera

**Comment by Niweera** [comment]
> Great job @Niweera

Thank you bröthër 🙏
